---
dependency:
  name: galaxy
  enabled: false
driver:
  name: vagrant
platforms:
  - name: instance
provisioner:
  name: ansible
  box: ubuntu/focal64
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
